apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: ${VELERO_NAMESPACE}
spec:
  template:
    spec:
      containers:
        - name: velero
          env:
          - name: HTTP_PROXY
            value: ${PROXY_ADDRESS}
          - name: HTTPS_PROXY
            value: ${PROXY_ADDRESS}
          - name: NO_PROXY
            value: ${NO_PROXY_ADDRESSES}
