resources:
- default.yaml
- ns.yaml
- adapter.yaml

patches:
- target:
    group: ""
    version: v1 # apiVersion
    kind: Service
    name: k8s
  path: prometheus-service.yaml
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: prometheus-node-exporter
  path: matchlabel-release.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: prometheus-operator
  path: matchlabel-release.yaml
