apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
  name: "base"
spec:
  kubernetes:
    version: 1.16.4
    serviceCIDR: 10.96.0.0/12
    serviceSubnetSize: "/32"
    bootstrapToken: 12xsr3d
    bootstrapTokenTTL: 89f9d88df9
    HACluster: true
    loadBalancerAddress: "1.232"
    kubernetesUpgradePatchVersion: true
    kubernetesMasterAddress: 192.13.4.3
    apiServiceAddress: 192.168.1.1
    kubeadmTokenCAHash: dfljfgdl
    controlPlane: true
    certKey: "secret"
  docker:
    version: latest
    bypassStorageDriverWarnings: false
    hardFailOnLoopback: false
    noCEOnEE: false
    noDocker: false
    additionalNoProxy: 2.3.1.3/32
    dockerRegistryIP: 127.0.0.1
  weave:
    version: latest
    encryptNetwork: true
    IPAllocRange: 10.32.0.0/12
    podCIDRRange: "/32"
    podCIDR: "1.1.1.1"
  contour:
    version: latest
    disableCountour: true
  rook:
    version: latest
    storageClass: default
    cephPoolReplicas: 1
  registry:
    version: latest
    registryPublishPort: "2323"
  prometheus:
    version: latest
  fluentd:
    version: latest
    efkStack: true
  kotsadm:
    version: latest
    applicationSlug: sentry
    uiBindPort: 8800
    kotsadmApplicationNamepsaces: "best"
    kotsadmHostname: 192.168.2.2
    kotsadmAlpha: "alpha"
  velero:
    version: latest
    namespace: velero
    installCLI: false
    useRestic: false
    LocalBucket: false
  minio:
    version: "latest"
    minioNamespace: "minio"
  openEBS:
    version: "latest"
    openEBSLocalPV: "strongpv"
    openEBSLocalPVStorageClass: "gym"
    openEBSNamespace: "openebs"
  flags:
    isKurl: True
    airgap: true
    hostnameCheck: "test"
    HTTPProxy: "1.1.1."
    noProxy: false
    publicAddress: 38.3.5.3
    privateAddress: 10.32.45.5
    hardFailOnFirewalld: true
    bypassFirewalldWarning: false
    Task: "important"
