resources:
- crds.yaml

patches:
- target:
    group: "apiextensions.k8s.io"
    version: v1 # apiVersion
    kind: CustomResourceDefinition
    name: alertmanagers.monitoring.coreos.com
  path: preserveUnknown.yaml
- target:
    group: "apiextensions.k8s.io"
    version: v1 # apiVersion
    kind: CustomResourceDefinition
    name: prometheuses.monitoring.coreos.com
  path: preserveUnknown.yaml
- target:
    group: "apiextensions.k8s.io"
    version: v1 # apiVersion
    kind: CustomResourceDefinition
    name: podmonitors.monitoring.coreos.com
  path: preserveUnknown.yaml
- target:
    group: "apiextensions.k8s.io"
    version: v1 # apiVersion
    kind: CustomResourceDefinition
    name: servicemonitors.monitoring.coreos.com
  path: preserveUnknown.yaml
