version: 2

defaults: &defaults
  docker:
  - image: replicated/gitops-builder:node8-go12
  working_directory: ~/repo
  environment: &environment
    PROJECT_NAME: kurl
    ECR_REPO: 923411875752.dkr.ecr.us-east-1.amazonaws.com
    OVERLAY_PATH: kustomize/overlays/staging
    GITOPS_BRANCH: master
    DOCKERFILE: deploy/Dockerfile-slim

jobs:
  is_upstream:
    docker:
      - image: circleci/python:3
    steps:
      - run: |
          set -veuo pipefail
          if [ "${CIRCLE_PROJECT_USERNAME}" != "replicatedhq" ]; then
            echo "refusing to build fork \"${CIRCLE_PROJECT_USERNAME}\""
            exit 1
          fi

  test:
    <<: *defaults
    steps:
      - checkout
      - run: sudo apt-get update; sudo apt-get install shunit2
      - run: sudo pip install pytest # todo cache these
      - run: sudo make deps # todo cache these
      - run: make test

  build_ubuntu16_docker:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build/ubuntu-16.04/packages/docker
      - persist_to_workspace:
          root: build
          paths:
            - ubuntu-16.04/packages/docker

  build_ubuntu18_docker:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build/ubuntu-18.04/packages/docker
      - persist_to_workspace:
          root: build
          paths:
            - ubuntu-18.04/packages/docker

  build_rhel7_docker:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build/rhel-7/packages/docker
      - persist_to_workspace:
          root: build
          paths:
            - rhel-7/packages/docker

  build_ubuntu16_k8s:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build/ubuntu-16.04/packages/k8s
      - persist_to_workspace:
          root: build
          paths:
            - ubuntu-16.04/packages/k8s

  build_ubuntu18_k8s:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build/ubuntu-18.04/packages/k8s
      - persist_to_workspace:
          root: build
          paths:
            - ubuntu-18.04/packages/k8s

  build_rhel7_k8s:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build/rhel-7/packages/k8s
      - persist_to_workspace:
          root: build
          paths:
            - rhel-7/packages/k8s

  build_k8s_images:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build/k8s-images.tar
      - persist_to_workspace:
          root: build
          paths:
            - k8s-images.tar

  build_dist:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: build
      - run: make code
      - run: make dist

  build_staging_docker_image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - attach_workspace:
          at: build
      - run: make code
      - run: make dist
      - run: make staging
      - run: |
          export WORKDIR=`pwd`
          export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
          build-docker
      - deploy:
          name: push image
          command: |
            export AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY
            export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
            push-docker

  build_production_docker_image:
    <<: *defaults
    environment:
      <<: *environment
      ECR_REPO: 799720048698.dkr.ecr.us-east-1.amazonaws.com
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - attach_workspace:
          at: build
      - run: make code
      - run: make dist
      - run: make staging
      - run: |
          export WORKDIR=`pwd`
          export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
          build-docker
      - deploy:
          name: push image
          command: |
            export AWS_ACCESS_KEY_ID=$PRODUCTION_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PRODUCTION_AWS_SECRET_ACCESS_KEY
            export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
            push-docker

  deploy_staging_eks:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "25:51:68:66:6d:12:c7:84:f4:18:97:6a:7c:2e:f8:3d"
      - deploy:
          name: Maybe deploy staging to eks
          command: |
            export WORKDIR=`pwd`
            export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
            deploy

  deploy_production_eks:
    <<: *defaults
    environment:
      <<: *environment
      ECR_REPO: 799720048698.dkr.ecr.us-east-1.amazonaws.com
      OVERLAY_PATH: kustomize/overlays/production
      GITOPS_BRANCH: release
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "25:51:68:66:6d:12:c7:84:f4:18:97:6a:7c:2e:f8:3d"
      - deploy:
          name: Maybe deploy production to eks
          command: |
            export WORKDIR=`pwd`
            export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
            deploy


workflows:
  version: 2

  pull-request:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

  master:
    jobs:
      - is_upstream:
          filters:
            branches:
              only: master

      - build_ubuntu16_docker:
          requires:
            - is_upstream
      - build_ubuntu18_docker:
          requires:
            - is_upstream
      - build_rhel7_docker:
          requires:
            - is_upstream
      - build_ubuntu16_k8s:
          requires:
            - is_upstream
      - build_ubuntu18_k8s:
          requires:
            - is_upstream
      - build_rhel7_k8s:
          requires:
            - is_upstream
      - build_k8s_images:
          requires:
            - is_upstream
      - build_staging_docker_image:
          requires:
            - build_ubuntu16_docker
            - build_ubuntu18_docker
            - build_rhel7_docker
            - build_ubuntu16_k8s
            - build_ubuntu18_k8s
            - build_rhel7_k8s
            - build_k8s_images
      - deploy_staging_eks:
          requires:
            - build_staging_docker_image
