version: 2

references:
  defaults: &defaults
    docker:
    - image: replicated/gitops-builder:node8-go12
    working_directory: ~/repo
    environment: &environment
      PROJECT_NAME: kurl
      ECR_REPO: 923411875752.dkr.ecr.us-east-1.amazonaws.com
      OVERLAY_PATH: kustomize/overlays/staging
      GITOPS_BRANCH: master
      DOCKERFILE: deploy/Dockerfile-slim

  tag_filters: &tag_filters
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

jobs:
  is_upstream:
    docker:
      - image: circleci/python:3
    steps:
      - run: |
          set -veuo pipefail
          if [ "${CIRCLE_PROJECT_USERNAME}" != "replicatedhq" ]; then
            echo "refusing to build fork \"${CIRCLE_PROJECT_USERNAME}\""
            exit 1
          fi
  
  test:
    <<: *defaults
    steps:
      - checkout
      - run: make -C web test
      - run: make -C kurl_util deps test

  kurl_util_image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: build and push kurl util image
          command: |
            set -veuo pipefail
            source bin/kurl-util-image-export.sh
            echo "$DOCKERHUB_DOCKER_PASS" | docker login -u $DOCKERHUB_DOCKER_USER --password-stdin
            make -C kurl_util build-and-push-kurl-util-image

  upload_staging_packages:
    <<: *defaults
    parallelism: 8
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: upload packages
          command: |
            export AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY
            export S3_BUCKET=kurl-sh-staging
            source bin/kurl-util-image-export.sh
            bin/upload-dist.sh

  upload_production_packages:
    <<: *defaults
    parallelism: 8
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: upload packages
          command: |
            export AWS_ACCESS_KEY_ID=$PRODUCTION_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PRODUCTION_AWS_SECRET_ACCESS_KEY
            export S3_BUCKET=kurl-sh
            source bin/kurl-util-image-export.sh
            bin/upload-dist.sh

  build_staging_docker_image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run: make -C web deps build
      - run: make web
      - run: |
          export WORKDIR=`pwd`
          export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
          source bin/kurl-util-image-export.sh
          bin/build-docker.sh
      - deploy:
          name: push image
          command: |
            export AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY
            export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
            push-docker

  build_production_docker_image:
    <<: *defaults
    environment:
      <<: *environment
      ECR_REPO: 799720048698.dkr.ecr.us-east-1.amazonaws.com
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run: make -C web deps build
      - run: make web
      - run: |
          export WORKDIR=`pwd`
          export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
          source bin/kurl-util-image-export.sh
          bin/build-docker.sh
      - deploy:
          name: push image
          command: |
            export AWS_ACCESS_KEY_ID=$PRODUCTION_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PRODUCTION_AWS_SECRET_ACCESS_KEY
            export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
            push-docker

  deploy_staging_eks:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "25:51:68:66:6d:12:c7:84:f4:18:97:6a:7c:2e:f8:3d"
      - deploy:
          name: Maybe deploy staging to eks
          command: |
            export WORKDIR=`pwd`
            export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
            deploy

  deploy_production_eks:
    <<: *defaults
    environment:
      <<: *environment
      ECR_REPO: 799720048698.dkr.ecr.us-east-1.amazonaws.com
      OVERLAY_PATH: kustomize/overlays/production
      GITOPS_BRANCH: release
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "25:51:68:66:6d:12:c7:84:f4:18:97:6a:7c:2e:f8:3d"
      - deploy:
          name: Maybe deploy production to eks
          command: |
            export WORKDIR=`pwd`
            export CIRCLE_PROJECT_REPONAME=$PROJECT_NAME
            deploy


workflows:
  version: 2

  pull-request:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

  staging:
    jobs:
      - is_upstream:
          filters:
            branches:
              only:
                - master
                - beta
                - ethan/testing

      - kurl_util_image:
          requires:
            - is_upstream
      - upload_staging_packages:
          requires:
            - kurl_util_image
      - build_staging_docker_image:
          requires:
            - kurl_util_image
      - deploy_staging_eks:
          requires:
            - build_staging_docker_image
            - upload_staging_packages

  tag:
    jobs:
      - is_upstream:
          filters:
            <<: *tag_filters

      - kurl_util_image:
          filters:
            <<: *tag_filters
          requires:
            - is_upstream
      - build_production_docker_image:
          filters:
            <<: *tag_filters
          requires:
            - kurl_util_image
      - upload_production_packages:
          filters:
            <<: *tag_filters
          requires:
            - kurl_util_image
      - deploy_production_eks:
          filters:
            <<: *tag_filters
          requires:
            - upload_production_packages
            - build_production_docker_image
