resources:
- prometheus-operator-0alertmanagerCustomResourceDefinition.yaml 
- prometheus-operator-0prometheusCustomResourceDefinition.yaml 
- prometheus-operator-0prometheusruleCustomResourceDefinition.yaml 
- prometheus-operator-deployment.yaml 
- prometheus-operator-0servicemonitorCustomResourceDefinition.yaml 
- prometheus-operator-service.yaml 
- prometheus-operator-0podmonitorCustomResourceDefinition.yaml 
- prometheus-operator-0alertmanagerConfigCustomResourceDefinition.yaml 
- prometheus-operator-0thanosrulerCustomResourceDefinition.yaml 
- 0namespace-namespace.yaml 
- prometheus-operator-clusterRoleBinding.yaml 
- prometheus-operator-clusterRole.yaml 
- prometheus-operator-0probeCustomResourceDefinition.yaml 
- prometheus-operator-serviceAccount.yaml
