apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgapi
spec:
  replicas: 3
  template:
    spec:
      nodeSelector:
        replicated/node-pool: privileged
      containers:
        - name: tgapi
          image: 799720048698.dkr.ecr.us-east-1.amazonaws.com/tgapi
          envFrom:
            - secretRef:
                name: tgapi
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: PROJECT_NAME
              value: "kurl"
            - name: USE_EC2_PARAMETERS
              value: "1"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: testgrid-postgres
                  key: uri
            - name: SUPPORT_BUNDLE_BUCKET
              value: "testgrid-bundles-production"
