# Source: rook-ceph/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  labels:
    operator: rook
    storage-backend: ceph
    chart: "rook-ceph-v1.5.9"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-operator
  template:
    metadata:
      labels:
        app: rook-ceph-operator
        chart: "rook-ceph-v1.5.9"
    spec:
      containers:
      - name: rook-ceph-operator
        image: "rook/ceph:v1.5.9"
        imagePullPolicy: IfNotPresent
        args: ["ceph", "operator"]
        env:
        - name: ROOK_CURRENT_NAMESPACE_ONLY
          value: "false"
        - name: AGENT_PRIORITY_CLASS_NAME
          value: rook-critical
        - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
          value: "false"
        - name: ROOK_LOG_LEVEL
          value: INFO
        - name: ROOK_ENABLE_SELINUX_RELABELING
          value: "true"
        - name: ROOK_DISABLE_DEVICE_HOTPLUG
          value: "false"
        - name: ROOK_CSI_ENABLE_RBD
          value: "true"
        - name: ROOK_CSI_ENABLE_CEPHFS
          value: "true"
        - name: CSI_ENABLE_CEPHFS_SNAPSHOTTER
          value: "true"
        - name: CSI_ENABLE_RBD_SNAPSHOTTER
          value: "true"
        - name: CSI_PLUGIN_PRIORITY_CLASSNAME
          value: "rook-critical"
        - name: CSI_PROVISIONER_PRIORITY_CLASSNAME
          value: "rook-critical"
        - name: CSI_ENABLE_OMAP_GENERATOR
          value: "false"
        - name: CSI_RBD_FSGROUPPOLICY
          value: "ReadWriteOnceWithFSType"
        - name: CSI_CEPHFS_FSGROUPPOLICY
          value: "ReadWriteOnceWithFSType"
        - name: ROOK_CSI_ENABLE_GRPC_METRICS
          value: "true"
        - name: CSI_FORCE_CEPHFS_KERNEL_CLIENT
          value: "true"
        - name: ROOK_ENABLE_FLEX_DRIVER
          value: "false"
        - name: ROOK_ENABLE_DISCOVERY_DAEMON
          value: "true"
        - name: ROOK_OBC_WATCH_OPERATOR_NAMESPACE
          value: "true"

        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ROOK_UNREACHABLE_NODE_TOLERATION_SECONDS
          value: "5"
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      serviceAccountName: rook-ceph-system
