resources:
- toolbox.yaml
- deployment.yaml
- rolebinding.yaml
- role.yaml
- clusterrolebinding.yaml
- clusterrole.yaml
- resources.yaml
- serviceaccount.yaml
- psp.yaml
- namespace.yaml
- priority-class.yaml
- configmap-rook-config-override.yaml
