apiVersion: apps/v1
kind: Deployment
metadata:
  name: kurl
spec:
  replicas: 3
  template:
    spec:
      nodeSelector:
        replicated/node-pool: privileged
      containers:
      - name: server
        image: 799720048698.dkr.ecr.us-east-1.amazonaws.com/kurl
        env:
        - name: KURL_BUCKET
          value: kurl-sh
      - name: kurl
        image: 799720048698.dkr.ecr.us-east-1.amazonaws.com/kurl
        env:
        - name: AWS_REGION
          value: us-east-1
        - name: PROJECT_NAME
          value: "kurl"
        - name: USE_EC2_PARAMETERS
          value: "1"
        - name: KURL_URL
          value: https://kurl.sh
        - name: KURL_BUCKET
          value: kurl-sh
        - name: NODE_ENV
          value: production
