apiVersion: apps/v1
kind: Deployment
metadata:
  name: kurl
spec:
  replicas: 3
  template:
    spec:
      nodeSelector:
        replicated/node-pool: privileged
      containers:
      - name: server
        image: 799720048698.dkr.ecr.us-east-1.amazonaws.com/kurl
        envFrom:
        - secretRef:
            name: kurl-secrets
        resources:
          requests:
            cpu: 550m
            memory: 200Mi
          limits:
            cpu: 2.5
            memory: 1600Mi
        env:
        - name: ENVIRONMENT
          value: production
      - name: kurl
        image: 799720048698.dkr.ecr.us-east-1.amazonaws.com/kurl
        envFrom:
        - secretRef:
            name: kurl-secrets
        resources:
          requests:
            cpu: 50m
            memory: 120Mi
          limits:
            cpu: 100m
            memory: 180Mi
        env:
        - name: AWS_REGION
          value: us-east-1
        - name: PROJECT_NAME
          value: "kurl"
        - name: USE_EC2_PARAMETERS
          value: "1"
        - name: KURL_URL
          value: https://kurl.sh
        - name: KURL_BUCKET
          value: kurl-sh
        - name: NODE_ENV
          value: production
        - name: KURL_UTIL_IMAGE
          value: replicated/kurl-util:__VERSION_TAG__
        - name: KURL_VERSION
          value: __VERSION_TAG__
