installer:
  spec:
    kubernetes:
      version: latest
    containerd:
      version: latest
    weave:
      version: latest
    prometheus:
      version: latest
      serviceType: "LoadBalancer"
output:
  - message: Prometheus service types are NodePort and ClusterIP, not LoadBalancer
    field: spec.prometheus.serviceType
    type: misconfiguration
