###############################################################################
# This action will automatically approve and merge dependabot PR's with updates
# to minor and patch versions if they pass all branch protection rules including
# status checks.
###############################################################################

name: dependabot-automerge

# This workflow trigger may lead to malicious PR authors being able to obtain repository write
# permissions or stealing repository secrets. 
# Please read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:

  auto-merge:
    runs-on: ubuntu-latest

    # Only run for dependabot pull requests
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:

      - name: Wait for build-test
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-build-test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build-test-success
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Job build-test success
        if: ${{ steps.wait-build-test.outputs.conclusion == 'success' }}
        run: echo "::notice ::build-test success"

      - name: Job build-test failure
        if: ${{ steps.wait-build-test.outputs.conclusion != 'success' }}
        run: |
          echo "::notice ::build-test conclusion ${{ github.event.workflow_run.conclusion }}"
          exit 1

      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-approve conditions
        id: auto-approve-conditions
        # Only auto-approve if this is a minor or patch version update
        if: |
          (
            steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
          ) || (
            steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor'
          )
        run: echo "::notice ::auto-approve conditions satisfied"

      - name: Create shortcut story if auto-merge conditions are not satisfied
        if: ${{ steps.auto-approve-conditions.conclusion != 'success' }}
        run: |
          EXISTING_STORY="$(curl -X GET \
            -H "Content-Type: application/json" \
            -H "Shortcut-Token: ${SHORTCUT_API_TOKEN}" \
            -d "{ \"page_size\": 1, \"query\": \"title:\\\"Automerge Failed for #${PR_NUMBER}\\\"\" }" \
            -L "https://api.app.shortcut.com/api/v3/search/stories")"
          if echo "${EXISTING_STORY}" | grep -q "Automerge Failed for #${PR_NUMBER} " ; then
            echo "::notice ::shortcut story already exists"
            exit 0
          fi

          PR_BODY="$(echo "${PR_BODY}" | sed -n '/--/q;p')"

          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Shortcut-Token: ${SHORTCUT_API_TOKEN}" \
            -d "{ \
              \"group_id\": \"6125060f-c490-4005-8dd7-165aa0b9cc18\", \
              \"owner_ids\": [\"61118e83-225b-4bff-9ae1-e5342ae0868f\"], \
              \"name\": \"Automerge Failed for #${PR_NUMBER} - '${PR_TITLE//\"/\\\"}'\", \
              \"story_type\": \"chore\", \
              \"description\": \"Dependabot was unable to automatically merge package update.\\n\\n${PR_BODY//\"/\\\"}\", \
              \"workflow_state_id\": 500122316, \
              \"estimate\": 1 }" \
            -L "https://api.app.shortcut.com/api/v3/stories"

          echo "::notice ::shortcut story created"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHORTCUT_API_TOKEN: ${{ secrets.SHORTCUT_API_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}

      - name: Approve Dependabot PR
        if: ${{ steps.auto-approve-conditions.conclusion == 'success' }}
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Auto-merge will wait for the branch protection rules, including approval and required
      # status checks.
      - name: Enable auto-merge for Dependabot PR
        if: ${{ steps.auto-approve-conditions.conclusion == 'success' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
