name: cron-local-path-provisioner-update
on:
  schedule:
  - cron: '0 4 * * *'
  workflow_dispatch: {}

jobs:
  build-pr-local-path-provisioner:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Create Local Path Storage Update
      id: update
      working-directory: ./addons/local-path-provisioner/template
      run: |
        ./script.sh

    - name: Create Pull Request # creates a PR if there are differences
      uses: peter-evans/create-pull-request@v4.1.1
      id: cpr
      with:
        token: ${{ secrets.AUTOMATED_PR_GH_PAT }}
        commit-message: Create new Local Path Storage version
        title: 'Automated Local Path Storage version update ${{ steps.update.outputs.local-path-provisioner_version }}'
        branch: automation/update-local-path-provisioner
        delete-branch: true
        labels: |
          automated-pr
          local-path-provisioner
        draft: false
        base: "main"
        body: "Automated changes by the [cron-local-path-provisioner-update](https://github.com/replicatedhq/kURL/blob/main/.github/workflows/update-local-path-provisioner.yaml) GitHub action"

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
